baseURL = 'http://pages.evanacox.io/'
languageCode = 'en-us'
title = 'Evan Cox'
theme = "gokarna"

enableRobotsTXT = true

[params]
  footer = "Evan Cox"
  description = "Passionate software developer and C.S. student at Clemson University (May 2025)."
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/evan-cox-70b4bb208"},
    {name = "github", url = "https://github.com/evanacox"},
    {name = "email", url = "mailto:evanacox00@gmail.com"}
  ]

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"
    url = "/projects/"
    pre = "<span data-feather='code'></span>"
    name = "Projects"
    weight = 1

  [[menu.main]]
    identifier = "experience"
    url = "/experience/"
    pre = "<span data-feather='user'></span>"
    name = "Experience"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    url = "/contact/"
    pre = "<span data-feather='send'></span>"
    name = "Contact"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/evanacox"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false